version: "1"

services:
  - type: web
    runtime: docker
    name: library-api
    repo: https://github.com/gerardo-mundo/LibraryBackend/tree/development
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: Database__ConnectionString
        fromDatabase:
          name: library-db
          property: connectionString
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 70
      targetCPUPercent: 70
    healthCheckPath: /health

databases:
  - name: library-db
    databaseName: library_db
    user: sa
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all
    highAvailability:
      enabled: false
    postgresMajorVersion: "13"

envVarGroups:
  - name: common-settings
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: LOG_LEVEL
        value: Information

previewsEnabled: true
previewsExpireAfterDays: 7
