services:
  - type: web
    name: librarybackend
    env: docker
    dockerfilePath: ./LibraryBackend/Dockerfile
    buildCommand: ""
    startCommand: dotnet LibraryBackend.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ConnectionStrings__SQL_CONNECTIONSTRING
        fromDatabase:
          name: "${DB}"
          property: connectionString
      - key: JWT_KEY
        sync: false
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    region: oregon

databases:
  - type: mssql
    name: "${DB}"
    plan: free
    region: oregon
    user:
      name: sa
      password: "${SA_PASSWORD}"
