name: Deploy docker image to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to the GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build -t ghcr.io/gerardo-mundo/librarybackend:latest -f LibraryBackend/Dockerfile ./LibraryBackend

    - name: Verify Docker image
      run: docker images

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/gerardo-mundo/librarybackend:latest

    - name: Log in to Heroku Container Registry
      run: echo ${{ secrets.API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.API_KEY }}
      run: |
        heroku container:login
        docker tag ghcr.io/gerardo-mundo/librarybackend:latest registry.heroku.com/${{ secrets.HEROKU_API_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_API_NAME }}/web
        heroku container:release web --app ${{ secrets.HEROKU_API_NAME }}
