name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to the GitHub Container Registry
      run: docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build -t ghcr.io/gerardo-mundo/librarybackend:latest -f LibraryBackend/Dockerfile ./LibraryBackend

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/gerardo-mundo/librarybackend:latest

    - name: Log in to Heroku Container Registry
      run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

    - name: Deploy to Heroku
      run: |
        heroku container:push web --app library-api
        heroku container:release web --app library-api
